// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/proto/upload/upload.proto

package uploadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadAvatarMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Avatars       []byte                 `protobuf:"bytes,2,opt,name=avatars,proto3" json:"avatars,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarMessage) Reset() {
	*x = UploadAvatarMessage{}
	mi := &file_api_v1_proto_upload_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarMessage) ProtoMessage() {}

func (x *UploadAvatarMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_upload_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarMessage.ProtoReflect.Descriptor instead.
func (*UploadAvatarMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_upload_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadAvatarMessage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadAvatarMessage) GetAvatars() []byte {
	if x != nil {
		return x.Avatars
	}
	return nil
}

func (x *UploadAvatarMessage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_api_v1_proto_upload_upload_proto protoreflect.FileDescriptor

const file_api_v1_proto_upload_upload_proto_rawDesc = "" +
	"\n" +
	" api/v1/proto/upload/upload.proto\x12\x13api.v1.proto.upload\"o\n" +
	"\x13UploadAvatarMessage\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\aavatars\x18\x02 \x01(\fR\aavatars\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentTypeB2Z0singkatin-api/proto/api/v1/proto/upload;uploadpbb\x06proto3"

var (
	file_api_v1_proto_upload_upload_proto_rawDescOnce sync.Once
	file_api_v1_proto_upload_upload_proto_rawDescData []byte
)

func file_api_v1_proto_upload_upload_proto_rawDescGZIP() []byte {
	file_api_v1_proto_upload_upload_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_upload_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_proto_upload_upload_proto_rawDesc), len(file_api_v1_proto_upload_upload_proto_rawDesc)))
	})
	return file_api_v1_proto_upload_upload_proto_rawDescData
}

var file_api_v1_proto_upload_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_v1_proto_upload_upload_proto_goTypes = []any{
	(*UploadAvatarMessage)(nil), // 0: api.v1.proto.upload.UploadAvatarMessage
}
var file_api_v1_proto_upload_upload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_proto_upload_upload_proto_init() }
func file_api_v1_proto_upload_upload_proto_init() {
	if File_api_v1_proto_upload_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_proto_upload_upload_proto_rawDesc), len(file_api_v1_proto_upload_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_proto_upload_upload_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_upload_upload_proto_depIdxs,
		MessageInfos:      file_api_v1_proto_upload_upload_proto_msgTypes,
	}.Build()
	File_api_v1_proto_upload_upload_proto = out.File
	file_api_v1_proto_upload_upload_proto_goTypes = nil
	file_api_v1_proto_upload_upload_proto_depIdxs = nil
}
