// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/proto/shortener/shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shortener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullUrl       string                 `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Visited       int64                  `protobuf:"varint,4,opt,name=visited,proto3" json:"visited,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shortener) Reset() {
	*x = Shortener{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shortener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shortener) ProtoMessage() {}

func (x *Shortener) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shortener.ProtoReflect.Descriptor instead.
func (*Shortener) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *Shortener) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shortener) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *Shortener) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *Shortener) GetVisited() int64 {
	if x != nil {
		return x.Visited
	}
	return 0
}

func (x *Shortener) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ExistsByShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByShortURLRequest) Reset() {
	*x = ExistsByShortURLRequest{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByShortURLRequest) ProtoMessage() {}

func (x *ExistsByShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByShortURLRequest.ProtoReflect.Descriptor instead.
func (*ExistsByShortURLRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ExistsByShortURLRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ExistsByShortURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExistsByShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByShortURLResponse) Reset() {
	*x = ExistsByShortURLResponse{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByShortURLResponse) ProtoMessage() {}

func (x *ExistsByShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByShortURLResponse.ProtoReflect.Descriptor instead.
func (*ExistsByShortURLResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ExistsByShortURLResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ListShortenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortenerRequest) Reset() {
	*x = ListShortenerRequest{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortenerRequest) ProtoMessage() {}

func (x *ListShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortenerRequest.ProtoReflect.Descriptor instead.
func (*ListShortenerRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ListShortenerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListShortenerRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShortenerRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListShortenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shorteners    []*Shortener           `protobuf:"bytes,1,rep,name=shorteners,proto3" json:"shorteners,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortenerResponse) Reset() {
	*x = ListShortenerResponse{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortenerResponse) ProtoMessage() {}

func (x *ListShortenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortenerResponse.ProtoReflect.Descriptor instead.
func (*ListShortenerResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ListShortenerResponse) GetShorteners() []*Shortener {
	if x != nil {
		return x.Shorteners
	}
	return nil
}

func (x *ListShortenerResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListShortenerResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShortenerResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetShortenerByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortenerByIDRequest) Reset() {
	*x = GetShortenerByIDRequest{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortenerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenerByIDRequest) ProtoMessage() {}

func (x *GetShortenerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenerByIDRequest.ProtoReflect.Descriptor instead.
func (*GetShortenerByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetShortenerByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShortenerByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shortener     *Shortener             `protobuf:"bytes,1,opt,name=shortener,proto3" json:"shortener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortenerByIDResponse) Reset() {
	*x = GetShortenerByIDResponse{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortenerByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenerByIDResponse) ProtoMessage() {}

func (x *GetShortenerByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenerByIDResponse.ProtoReflect.Descriptor instead.
func (*GetShortenerByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *GetShortenerByIDResponse) GetShortener() *Shortener {
	if x != nil {
		return x.Shortener
	}
	return nil
}

type CreateShortenerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullUrl       string                 `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortenerMessage) Reset() {
	*x = CreateShortenerMessage{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortenerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenerMessage) ProtoMessage() {}

func (x *CreateShortenerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenerMessage.ProtoReflect.Descriptor instead.
func (*CreateShortenerMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *CreateShortenerMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShortenerMessage) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *CreateShortenerMessage) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortenerMessage) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type UpdateVisitorCountMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Referer       string                 `protobuf:"bytes,4,opt,name=referer,proto3" json:"referer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVisitorCountMessage) Reset() {
	*x = UpdateVisitorCountMessage{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVisitorCountMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVisitorCountMessage) ProtoMessage() {}

func (x *UpdateVisitorCountMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVisitorCountMessage.ProtoReflect.Descriptor instead.
func (*UpdateVisitorCountMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateVisitorCountMessage) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UpdateVisitorCountMessage) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *UpdateVisitorCountMessage) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UpdateVisitorCountMessage) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

type UpdateShortenerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullUrl       string                 `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShortenerMessage) Reset() {
	*x = UpdateShortenerMessage{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShortenerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortenerMessage) ProtoMessage() {}

func (x *UpdateShortenerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortenerMessage.ProtoReflect.Descriptor instead.
func (*UpdateShortenerMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateShortenerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateShortenerMessage) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *UpdateShortenerMessage) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type DeleteShortenerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortenerMessage) Reset() {
	*x = DeleteShortenerMessage{}
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortenerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortenerMessage) ProtoMessage() {}

func (x *DeleteShortenerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortenerMessage.ProtoReflect.Descriptor instead.
func (*DeleteShortenerMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteShortenerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_v1_proto_shortener_shortener_proto protoreflect.FileDescriptor

const file_api_v1_proto_shortener_shortener_proto_rawDesc = "" +
	"\n" +
	"&api/v1/proto/shortener/shortener.proto\x12\x16api.v1.proto.shortener\"\x8c\x01\n" +
	"\tShortener\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bfull_url\x18\x02 \x01(\tR\afullUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x18\n" +
	"\avisited\x18\x04 \x01(\x03R\avisited\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"F\n" +
	"\x17ExistsByShortURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"2\n" +
	"\x18ExistsByShortURLResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"Y\n" +
	"\x14ListShortenerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\xa5\x01\n" +
	"\x15ListShortenerResponse\x12A\n" +
	"\n" +
	"shorteners\x18\x01 \x03(\v2!.api.v1.proto.shortener.ShortenerR\n" +
	"shorteners\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\")\n" +
	"\x17GetShortenerByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x18GetShortenerByIDResponse\x12?\n" +
	"\tshortener\x18\x01 \x01(\v2!.api.v1.proto.shortener.ShortenerR\tshortener\"\x88\x01\n" +
	"\x16CreateShortenerMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bfull_url\x18\x02 \x01(\tR\afullUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\x90\x01\n" +
	"\x19UpdateVisitorCountMessage\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x18\n" +
	"\areferer\x18\x04 \x01(\tR\areferer\"`\n" +
	"\x16UpdateShortenerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bfull_url\x18\x02 \x01(\tR\afullUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\"(\n" +
	"\x16DeleteShortenerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xf9\x02\n" +
	"\x10ShortenerService\x12w\n" +
	"\x18GetListShortenerByUserID\x12,.api.v1.proto.shortener.ListShortenerRequest\x1a-.api.v1.proto.shortener.ListShortenerResponse\x12u\n" +
	"\x10ExistsByShortURL\x12/.api.v1.proto.shortener.ExistsByShortURLRequest\x1a0.api.v1.proto.shortener.ExistsByShortURLResponse\x12u\n" +
	"\x10GetShortenerByID\x12/.api.v1.proto.shortener.GetShortenerByIDRequest\x1a0.api.v1.proto.shortener.GetShortenerByIDResponseB8Z6singkatin-api/proto/api/v1/proto/shortener;shortenerpbb\x06proto3"

var (
	file_api_v1_proto_shortener_shortener_proto_rawDescOnce sync.Once
	file_api_v1_proto_shortener_shortener_proto_rawDescData []byte
)

func file_api_v1_proto_shortener_shortener_proto_rawDescGZIP() []byte {
	file_api_v1_proto_shortener_shortener_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_shortener_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_proto_shortener_shortener_proto_rawDesc), len(file_api_v1_proto_shortener_shortener_proto_rawDesc)))
	})
	return file_api_v1_proto_shortener_shortener_proto_rawDescData
}

var file_api_v1_proto_shortener_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_proto_shortener_shortener_proto_goTypes = []any{
	(*Shortener)(nil),                 // 0: api.v1.proto.shortener.Shortener
	(*ExistsByShortURLRequest)(nil),   // 1: api.v1.proto.shortener.ExistsByShortURLRequest
	(*ExistsByShortURLResponse)(nil),  // 2: api.v1.proto.shortener.ExistsByShortURLResponse
	(*ListShortenerRequest)(nil),      // 3: api.v1.proto.shortener.ListShortenerRequest
	(*ListShortenerResponse)(nil),     // 4: api.v1.proto.shortener.ListShortenerResponse
	(*GetShortenerByIDRequest)(nil),   // 5: api.v1.proto.shortener.GetShortenerByIDRequest
	(*GetShortenerByIDResponse)(nil),  // 6: api.v1.proto.shortener.GetShortenerByIDResponse
	(*CreateShortenerMessage)(nil),    // 7: api.v1.proto.shortener.CreateShortenerMessage
	(*UpdateVisitorCountMessage)(nil), // 8: api.v1.proto.shortener.UpdateVisitorCountMessage
	(*UpdateShortenerMessage)(nil),    // 9: api.v1.proto.shortener.UpdateShortenerMessage
	(*DeleteShortenerMessage)(nil),    // 10: api.v1.proto.shortener.DeleteShortenerMessage
}
var file_api_v1_proto_shortener_shortener_proto_depIdxs = []int32{
	0, // 0: api.v1.proto.shortener.ListShortenerResponse.shorteners:type_name -> api.v1.proto.shortener.Shortener
	0, // 1: api.v1.proto.shortener.GetShortenerByIDResponse.shortener:type_name -> api.v1.proto.shortener.Shortener
	3, // 2: api.v1.proto.shortener.ShortenerService.GetListShortenerByUserID:input_type -> api.v1.proto.shortener.ListShortenerRequest
	1, // 3: api.v1.proto.shortener.ShortenerService.ExistsByShortURL:input_type -> api.v1.proto.shortener.ExistsByShortURLRequest
	5, // 4: api.v1.proto.shortener.ShortenerService.GetShortenerByID:input_type -> api.v1.proto.shortener.GetShortenerByIDRequest
	4, // 5: api.v1.proto.shortener.ShortenerService.GetListShortenerByUserID:output_type -> api.v1.proto.shortener.ListShortenerResponse
	2, // 6: api.v1.proto.shortener.ShortenerService.ExistsByShortURL:output_type -> api.v1.proto.shortener.ExistsByShortURLResponse
	6, // 7: api.v1.proto.shortener.ShortenerService.GetShortenerByID:output_type -> api.v1.proto.shortener.GetShortenerByIDResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_proto_shortener_shortener_proto_init() }
func file_api_v1_proto_shortener_shortener_proto_init() {
	if File_api_v1_proto_shortener_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_proto_shortener_shortener_proto_rawDesc), len(file_api_v1_proto_shortener_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_proto_shortener_shortener_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_shortener_shortener_proto_depIdxs,
		MessageInfos:      file_api_v1_proto_shortener_shortener_proto_msgTypes,
	}.Build()
	File_api_v1_proto_shortener_shortener_proto = out.File
	file_api_v1_proto_shortener_shortener_proto_goTypes = nil
	file_api_v1_proto_shortener_shortener_proto_depIdxs = nil
}
