// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/v1/proto/shortener/shortener.proto

package shortenerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortenerService_GetListShortenerByUserID_FullMethodName = "/api.v1.proto.shortener.ShortenerService/GetListShortenerByUserID"
	ShortenerService_ExistsByShortURL_FullMethodName         = "/api.v1.proto.shortener.ShortenerService/ExistsByShortURL"
	ShortenerService_GetShortenerByID_FullMethodName         = "/api.v1.proto.shortener.ShortenerService/GetShortenerByID"
)

// ShortenerServiceClient is the client API for ShortenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortenerServiceClient interface {
	GetListShortenerByUserID(ctx context.Context, in *ListShortenerRequest, opts ...grpc.CallOption) (*ListShortenerResponse, error)
	ExistsByShortURL(ctx context.Context, in *ExistsByShortURLRequest, opts ...grpc.CallOption) (*ExistsByShortURLResponse, error)
	GetShortenerByID(ctx context.Context, in *GetShortenerByIDRequest, opts ...grpc.CallOption) (*GetShortenerByIDResponse, error)
}

type shortenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerServiceClient(cc grpc.ClientConnInterface) ShortenerServiceClient {
	return &shortenerServiceClient{cc}
}

func (c *shortenerServiceClient) GetListShortenerByUserID(ctx context.Context, in *ListShortenerRequest, opts ...grpc.CallOption) (*ListShortenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShortenerResponse)
	err := c.cc.Invoke(ctx, ShortenerService_GetListShortenerByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerServiceClient) ExistsByShortURL(ctx context.Context, in *ExistsByShortURLRequest, opts ...grpc.CallOption) (*ExistsByShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsByShortURLResponse)
	err := c.cc.Invoke(ctx, ShortenerService_ExistsByShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerServiceClient) GetShortenerByID(ctx context.Context, in *GetShortenerByIDRequest, opts ...grpc.CallOption) (*GetShortenerByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShortenerByIDResponse)
	err := c.cc.Invoke(ctx, ShortenerService_GetShortenerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServiceServer is the server API for ShortenerService service.
// All implementations must embed UnimplementedShortenerServiceServer
// for forward compatibility.
type ShortenerServiceServer interface {
	GetListShortenerByUserID(context.Context, *ListShortenerRequest) (*ListShortenerResponse, error)
	ExistsByShortURL(context.Context, *ExistsByShortURLRequest) (*ExistsByShortURLResponse, error)
	GetShortenerByID(context.Context, *GetShortenerByIDRequest) (*GetShortenerByIDResponse, error)
	mustEmbedUnimplementedShortenerServiceServer()
}

// UnimplementedShortenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortenerServiceServer struct{}

func (UnimplementedShortenerServiceServer) GetListShortenerByUserID(context.Context, *ListShortenerRequest) (*ListShortenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListShortenerByUserID not implemented")
}
func (UnimplementedShortenerServiceServer) ExistsByShortURL(context.Context, *ExistsByShortURLRequest) (*ExistsByShortURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExistsByShortURL not implemented")
}
func (UnimplementedShortenerServiceServer) GetShortenerByID(context.Context, *GetShortenerByIDRequest) (*GetShortenerByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShortenerByID not implemented")
}
func (UnimplementedShortenerServiceServer) mustEmbedUnimplementedShortenerServiceServer() {}
func (UnimplementedShortenerServiceServer) testEmbeddedByValue()                          {}

// UnsafeShortenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortenerServiceServer will
// result in compilation errors.
type UnsafeShortenerServiceServer interface {
	mustEmbedUnimplementedShortenerServiceServer()
}

func RegisterShortenerServiceServer(s grpc.ServiceRegistrar, srv ShortenerServiceServer) {
	// If the following call panics, it indicates UnimplementedShortenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortenerService_ServiceDesc, srv)
}

func _ShortenerService_GetListShortenerByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShortenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).GetListShortenerByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortenerService_GetListShortenerByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).GetListShortenerByUserID(ctx, req.(*ListShortenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerService_ExistsByShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsByShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).ExistsByShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortenerService_ExistsByShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).ExistsByShortURL(ctx, req.(*ExistsByShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerService_GetShortenerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortenerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).GetShortenerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortenerService_GetShortenerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).GetShortenerByID(ctx, req.(*GetShortenerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortenerService_ServiceDesc is the grpc.ServiceDesc for ShortenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.proto.shortener.ShortenerService",
	HandlerType: (*ShortenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListShortenerByUserID",
			Handler:    _ShortenerService_GetListShortenerByUserID_Handler,
		},
		{
			MethodName: "ExistsByShortURL",
			Handler:    _ShortenerService_ExistsByShortURL_Handler,
		},
		{
			MethodName: "GetShortenerByID",
			Handler:    _ShortenerService_GetShortenerByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/proto/shortener/shortener.proto",
}
